package administrador;

import Funciones.conexion;
import Funciones.utils.Utils;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Agregarempleado extends javax.swing.JFrame {

    Connection conn;
    Statement sent;

    public Agregarempleado() {
        initComponents();
        Etiquetas();
        conn = conexion.conectar();
        this.setLocationRelativeTo(null);
       
    }
    void Etiquetas(){
        anuncio.setText("<html>Llena todos los datos del empleado para realizar un registro exitoso</html>");
        ValNom.setText("<html>Debes ingresar un nombre.</html>");
        ValApe.setText("<html>Debes ingresar un apellido.</html>");
        ValUser.setText("<html>Debes ingresar un usuario.</html>");
        ValPass.setText("<html>Debes ingresar una contraseña.</html>");
        ValEmail.setText("<html>Debes ingresar un correo.<br>Ejemplo: ejemplo@ejemplo.com</html>");
    }
 void Validar() {
        if (jTextNombre.getText().isEmpty()) {
             ValNom.setForeground(Color.red);
        } else {
            ValNom.setText("");
        }
        if (jTextApellidos.getText().isEmpty()) {
             ValApe.setForeground(Color.red);
        } else {
            ValApe.setText("");
        }
        if (jTextUsuario.getText().isEmpty()) {
               ValUser.setText("<html>Debes ingresar un usuario.</html>");      
             ValUser.setForeground(Color.red);
        } else {
            ValUser.setText("");
        }
        if (jPasswordField1.getText().isEmpty()) {
            ValPass.setForeground(Color.red);
        } else {
            ValPass.setText("");
        }
        if (jTextCorreo.getText().isEmpty()) {
            ValEmail.setText("<html>Debes ingresar un correo.<br>Ejemplo: ejemplo@ejemplo.com</html>");
            ValEmail.setForeground(Color.red);
        } else {
            ValEmail.setText("");
        }
    }
    void Limpiar() {
        jTextNombre.setText("");
        jTextApellidos.setText("");
        jTextUsuario.setText("");
        jPasswordField1.setText("");
        jTextCorreo.setText("");
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/drogas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltexto1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextCorreo = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelIcon = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        ValNom = new javax.swing.JLabel();
        ValApe = new javax.swing.JLabel();
        ValUser = new javax.swing.JLabel();
        ValPass = new javax.swing.JLabel();
        ValEmail = new javax.swing.JLabel();
        anuncio = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltexto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabeltexto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltexto1.setText("REGISTRAR EMPLEADO");
        getContentPane().add(jLabeltexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 20));

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, -1));

        jTextApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, -1));
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 170, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 170, -1));
        getContentPane().add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 170, -1));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado_1.png"))); // NOI18N
        jLabelIcon.setMaximumSize(new java.awt.Dimension(300, 150));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(300, 150));
        getContentPane().add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 270, 260));

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 20));

        jLabelApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos:");
        getContentPane().add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 20));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        jLabelContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 20));

        jLabelCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 20));

        ValNom.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValNom.setForeground(new java.awt.Color(255, 255, 255));
        ValNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        ValApe.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValApe.setForeground(new java.awt.Color(255, 255, 255));
        ValApe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        ValUser.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValUser.setForeground(new java.awt.Color(255, 255, 255));
        ValUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        ValPass.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValPass.setForeground(new java.awt.Color(255, 255, 255));
        ValPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        ValEmail.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValEmail.setForeground(new java.awt.Color(255, 255, 255));
        ValEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        anuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        anuncio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(anuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient-blue-green-linear-1152x2048-c2-00008b-00ff7f-a-45-f-14.png"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        int caracteres = 4;
        String user = jTextUsuario.getText();
        String correo2 = jTextCorreo.getText();
        ValUser.setText("");
        ValEmail.setText("");
          
        
        if (jTextNombre.getText().equals("") || jTextApellidos.getText().equals("")
                || jTextUsuario.getText().equals("") || jPasswordField1.getText().equals("")
                || jTextCorreo.getText().equals("")) {
            Validar();
            JOptionPane.showMessageDialog(null, "Faltan campos");
        } else {
            if (!Utils.verifCorreo(jTextCorreo.getText())) {
                Validar();
                ValEmail.setText("<html>Debes ingresar un correo valido.<br>Ejemplo: ejemplo@ejemplo.com</html>");
                ValEmail.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Correo Invalido");
            } else {
                if (correo2.equals(Utils.user("empleados", "Em_Correo", correo2)) && user.equals(Utils.user("empleados", "Em_Usuario", user))) {
                        Validar();
                        ValUser.setForeground(Color.red);
                        ValEmail.setForeground(Color.red);
                        ValEmail.setText("<html>Ya existe este correo.</html>");
                        ValUser.setText("<html>Ya existe este usuario.</html>");
                        JOptionPane.showMessageDialog(null, "Ya existe este usuario y/o correo.");
                    } else {
                     if (user.equals(Utils.user("empleados", "Em_Usuario", user))) {
                            Validar();
                            ValUser.setForeground(Color.red);
                            ValUser.setText("<html>Ya existe este usuario.</html>");
                            JOptionPane.showMessageDialog(null, "Ya existe este usuario.");
                        } else {
                         if (correo2.equals(Utils.user("empleados", "Em_Correo", correo2))) {
                                Validar();
                                 ValEmail.setForeground(Color.red);
                                ValEmail.setText("<html>Ya existe este correo.</html>");
                                JOptionPane.showMessageDialog(null, "Ya existe este correo.");
                            } else {
                try {
                    String sql = "insert into empleados (Em_Nombre,Em_Apellidos,Em_Usuario,Em_Contraseña,Em_Correo) values (?,?,?,?,?)";
                    PreparedStatement ps = conn.prepareCall(sql);
                    ps.setString(1, jTextNombre.getText());
                    ps.setString(2, jTextApellidos.getText());
                    ps.setString(3, jTextUsuario.getText());
                    ps.setString(4, jPasswordField1.getText());
                    ps.setString(5, jTextCorreo.getText());
                    int n = ps.executeUpdate();
                    if (n > 0) {
                        JOptionPane.showMessageDialog(null, "Datos guardados");
                    }

                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Error ->" + e.getMessage());
                }
                Limpiar();
                Etiquetas();
            }
           }
          }
        }
     }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        Utils.validNomApe(jTextNombre.getText(), evt);
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidosKeyTyped
        Utils.validNomApe(jTextApellidos.getText(), evt);
    }//GEN-LAST:event_jTextApellidosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregarempleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ValApe;
    private javax.swing.JLabel ValEmail;
    private javax.swing.JLabel ValNom;
    private javax.swing.JLabel ValPass;
    private javax.swing.JLabel ValUser;
    private javax.swing.JLabel anuncio;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabeltexto1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
