/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import Funciones.utils.Utils;
import empleado.VentasE;
import java.awt.Image;
import java.awt.Toolkit;
import farmacia.Login;

/**
 *
 * @author Guillermo
 */
public class Inicio extends javax.swing.JFrame {

    Modificar mo;
    Eliminarusuario elm;
    Eliminar el;
    Agregar ag;
    Agregarempleado agE;
    Consultar co;
    VentasE ve;
    ModificarEmpleado me;
    Login lo;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/drogas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregarEmpleado = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminarEmpleado = new javax.swing.JButton();
        jButtonModificarEmpleado = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVenta = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelAgregar = new javax.swing.JLabel();
        jLabelEliminarEmp1 = new javax.swing.JLabel();
        jLabelModificarEmp = new javax.swing.JLabel();
        jLabelAgregarEmpl = new javax.swing.JLabel();
        jLabelModificar = new javax.swing.JLabel();
        jLabelConsultar = new javax.swing.JLabel();
        jLabelVenta = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Farmacia \"Econofarm\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jButtonAgregar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar Producto");
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setContentAreaFilled(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 250, 30));

        jButtonAgregarEmpleado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonAgregarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarEmpleado.setText("Agregar Empleado");
        jButtonAgregarEmpleado.setBorderPainted(false);
        jButtonAgregarEmpleado.setContentAreaFilled(false);
        jButtonAgregarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, 30));

        jButtonConsultar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultar.setText("Consultar Producto");
        jButtonConsultar.setBorderPainted(false);
        jButtonConsultar.setContentAreaFilled(false);
        jButtonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 250, 30));

        jButtonModificar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar Producto");
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setContentAreaFilled(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificar.setPreferredSize(new java.awt.Dimension(263, 39));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 250, 30));

        jButtonEliminarEmpleado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonEliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarEmpleado.setText("Eliminar Empleado");
        jButtonEliminarEmpleado.setBorderPainted(false);
        jButtonEliminarEmpleado.setContentAreaFilled(false);
        jButtonEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 250, 30));

        jButtonModificarEmpleado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonModificarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarEmpleado.setText("Modificar Empleado");
        jButtonModificarEmpleado.setBorderPainted(false);
        jButtonModificarEmpleado.setContentAreaFilled(false);
        jButtonModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificarEmpleado.setPreferredSize(new java.awt.Dimension(289, 39));
        jButtonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 270, 30));

        jButtonEliminar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar Producto");
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setContentAreaFilled(false);
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, -1, 30));

        jButtonVenta.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButtonVenta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVenta.setText("Venta");
        jButtonVenta.setBorderPainted(false);
        jButtonVenta.setContentAreaFilled(false);
        jButtonVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 140, 30));

        jButtonSalir.setFont(new java.awt.Font("Century Schoolbook", 3, 24)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 100, 40));

        jLabelAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        getContentPane().add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, 140));

        jLabelEliminarEmp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLabelEliminarEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 140));

        jLabelModificarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar_Empleado.png"))); // NOI18N
        getContentPane().add(jLabelModificarEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, 140));

        jLabelAgregarEmpl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        getContentPane().add(jLabelAgregarEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, 140));

        jLabelModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        getContentPane().add(jLabelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 140, 140));

        jLabelConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa (1).png"))); // NOI18N
        getContentPane().add(jLabelConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 140, 140));

        jLabelVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carro-de-la-compra.png"))); // NOI18N
        getContentPane().add(jLabelVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 140, 140));

        jLabelEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bote-de-basura.png"))); // NOI18N
        getContentPane().add(jLabelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 140, 140));

        jButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close3.png"))); // NOI18N
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 5, 25, 25));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient-blue-green-linear-1152x2048-c2-00008b-00ff7f-a-45-f-14.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if (mo == null) {
            mo = new Modificar();
            mo.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        salir();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEmpleadoActionPerformed
        if (elm == null) {
            elm = new Eliminarusuario();
            elm.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonEliminarEmpleadoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if (el == null) {
            el = new Eliminar();
            el.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        if (ag == null) {
            ag = new Agregar();
            ag.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEmpleadoActionPerformed
        if (agE == null) {
            agE = new Agregarempleado();
            agE.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAgregarEmpleadoActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        if (co == null) {
            co = new Consultar();
            co.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentaActionPerformed
        if (ve == null) {
            ve = new VentasE(Utils.ADMIN);
            ve.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonVentaActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        salir();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEmpleadoActionPerformed
        if (me == null) {
            me = new ModificarEmpleado();
            me.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonModificarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    public void salir() {
        if (lo == null) {
            lo = new Login();
            lo.setVisible(true);
            this.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    public javax.swing.JButton jButtonAgregarEmpleado;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonEliminarEmpleado;
    private javax.swing.JButton jButtonModificar;
    public javax.swing.JButton jButtonModificarEmpleado;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelAgregarEmpl;
    private javax.swing.JLabel jLabelConsultar;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelEliminarEmp1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelModificar;
    private javax.swing.JLabel jLabelModificarEmp;
    private javax.swing.JLabel jLabelVenta;
    // End of variables declaration//GEN-END:variables
}
