/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import Funciones.conexion;
import Funciones.utils.Utils;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Guillermo
 */
public class ModificarEmpleado extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection conn;
    Statement sent;
    TableRowSorter trs;

    /**
     * Creates new form Modificar
     */
    public ModificarEmpleado() {
        initComponents();
        LlenarTabla();
        anuncio.setText("<html>Debes dar clic en un registro de la tabla para poder editar la información.</html>");
                anuncioB.setText("<html>NOTA: Puedes ingresar el nombre del empleado<br>en el cuadro de texto para poder realizar un filtrado.</html>");

        conn = conexion.conectar();
        this.setLocationRelativeTo(null);
    }
    void Validar() {
        int fila = jTable1.getSelectedRow();
        if (jTextNombre.getText().isEmpty()&& fila==1) {
         ValNom.setText("<html>Debes ingresar un nombre.</html>");
             ValNom.setForeground(Color.red);
        } else {
            ValNom.setText("");
        }
        if (jTextApellidos.getText().isEmpty() && fila==1) {
         ValApe.setText("<html>Debes ingresar un apellido.</html>");
            ValApe.setForeground(Color.red);
        } else {
            ValApe.setText("");
        }
        if (jTextUsuario.getText().isEmpty()&& fila==1) {
               ValUser.setText("<html>Debes ingresar un usuario.</html>");      
             ValUser.setForeground(Color.red);
        } else {
            ValUser.setText("");
        }
        if (jPasswordField1.getText().isEmpty()&& fila==1) {
        ValPass.setText("<html>Debes ingresar una contraseña.</html>");
            ValPass.setForeground(Color.red);
        } else {
            ValPass.setText("");
        }
        if (jTextCorreo.getText().isEmpty()&& fila==1) {
            ValEmail.setText("<html>Debes ingresar un correo.<br>Ejemplo: ejemplo@ejemplo.com</html>");
            ValEmail.setForeground(Color.red);
        } else {
            ValEmail.setText("");
        }
    }
    void Habilitar(){
        jTextNombre.enable();
        jTextApellidos.enable();
        jTextUsuario.enable();
        jPasswordField1.enable();
        jTextCorreo.enable();
    }
    void Deshabilitar(){
        jTextNombre.disable();
        jTextApellidos.disable();
        jTextUsuario.disable();
        jPasswordField1.disable();
        jTextCorreo.disable();
    }
    void LlenarTabla() {
        try {
            conn = conexion.conectar();
            String[] titulos = {"IdEmpleado", "Nombre", "Apellidos", "Usuario", "Contraseña", "Correo"};
            String sql = "Select * from empleados";
            model = new DefaultTableModel(null, titulos);
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            String[] fila = new String[6];
            while (rs.next()) {
                fila[0] = rs.getString("Em_Id");
                fila[1] = rs.getString("Em_Nombre");
                fila[2] = rs.getString("Em_Apellidos");
                fila[3] = rs.getString("Em_Usuario");
                fila[4] = rs.getString("Em_Contraseña");
                fila[5] = rs.getString("Em_Correo");
                model.addRow(fila);
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error ->" + e.getMessage());
        }
    }

    void Limpiar() {
        jTextNombre.setText("");
        jTextApellidos.setText("");
        jTextUsuario.setText("");
        jPasswordField1.setText("");
        jTextCorreo.setText("");
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/drogas.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTexto = new javax.swing.JLabel();
        jButtonCancelar1 = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextUsuario = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        anuncio = new javax.swing.JLabel();
        ValNom = new javax.swing.JLabel();
        ValApe = new javax.swing.JLabel();
        ValUser = new javax.swing.JLabel();
        ValPass = new javax.swing.JLabel();
        ValEmail = new javax.swing.JLabel();
        anuncioB = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTexto.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabelTexto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto.setText("Modificar Empleado");
        getContentPane().add(jLabelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 90, 40));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 90, 40));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 730, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 115, -1, -1));

        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 115, 280, -1));

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 70, 20));

        jLabelApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellidos.setText("Apellidos:");
        getContentPane().add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 20));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 90, 20));

        jLabelContraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 20));

        jLabelCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo:");
        getContentPane().add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 20));

        jTextCorreo.setEnabled(false);
        getContentPane().add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 200, -1));

        jPasswordField1.setEnabled(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 200, -1));

        jTextUsuario.setEnabled(false);
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 200, -1));

        jTextApellidos.setEnabled(false);
        jTextApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, -1));

        jTextNombre.setEnabled(false);
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 200, -1));

        anuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        anuncio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(anuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        ValNom.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValNom.setForeground(new java.awt.Color(255, 255, 255));
        ValNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        ValApe.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValApe.setForeground(new java.awt.Color(255, 255, 255));
        ValApe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        ValUser.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValUser.setForeground(new java.awt.Color(255, 255, 255));
        ValUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        ValPass.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValPass.setForeground(new java.awt.Color(255, 255, 255));
        ValPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        ValEmail.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        ValEmail.setForeground(new java.awt.Color(255, 255, 255));
        ValEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(ValEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        anuncioB.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        anuncioB.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(anuncioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient-blue-green-linear-1152x2048-c2-00008b-00ff7f-a-45-f-14.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int fila = jTable1.getSelectedRow();
        String user = jTextUsuario.getText();
        String correo2 = jTextCorreo.getText();
        Validar();
        if (fila == -1) {
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un empleado para que sea modificado.");
                    } else {
        if (jTextNombre.getText().equals("")
                || jTextApellidos.getText().equals("")
                || jTextUsuario.getText().equals("")
                || jPasswordField1.getText().equals("")
                || jTextCorreo.getText().equals("")) {
           
            JOptionPane.showMessageDialog(null, "Faltan campos");
        } else {
            if (!Utils.verifCorreo(jTextCorreo.getText())) {
                  ValEmail.setText("");
                ValEmail.setText("<html>Debes ingresar un correo.<br>Ejemplo: ejemplo@ejemplo.com</html>");
                ValEmail.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Correo Invalido");
            } else {
                if (correo2.equals(Utils.user("empleados", "Em_Correo", correo2)) && 
                    user.equals(Utils.user("empleados", "Em_Usuario", user))) {
                    ValUser.setText("");  
                    ValEmail.setText("");  
                    ValUser.setForeground(Color.red);
                        ValEmail.setForeground(Color.red);
                        ValEmail.setText("<html>Ya existe este correo.</html>");
                        ValUser.setText("<html>Ya existe este usuario.</html>");
                        JOptionPane.showMessageDialog(null, "Ya existe este usuario y/o correo.");
                    } else {
                    if (user.equals(Utils.user("empleados", "Em_Usuario", user))) {
                        ValUser.setText("");   
                        ValUser.setForeground(Color.red);
                            ValUser.setText("<html>Ya existe este usuario.</html>");
                            JOptionPane.showMessageDialog(null, "Ya existe este usuario.");
                        } else {
                         if (correo2.equals(Utils.user("empleados", "Em_Correo", correo2))) {
                                ValEmail.setText("");
                                 ValEmail.setForeground(Color.red);
                                ValEmail.setText("<html>Ya existe este correo.</html>");
                                JOptionPane.showMessageDialog(null, "Ya existe este correo.");
                            } else {
                try {
                    String sql = "update empleados set Em_Nombre=?,Em_Apellidos=?,Em_Usuario=?,Em_Contraseña=?,Em_Correo=? where Em_Id=?";
                    
                    
                        String dao = (String) jTable1.getValueAt(fila, 0);
                        PreparedStatement ps = conn.prepareCall(sql);
                        ps.setString(1, jTextNombre.getText());
                        ps.setString(2, jTextApellidos.getText());
                        ps.setString(3, jTextUsuario.getText());
                        ps.setString(4, jPasswordField1.getText());
                        ps.setString(5, jTextCorreo.getText());
                        ps.setString(6, dao);
                        int n = ps.executeUpdate();
                        if (n > 0) {
                            Limpiar();
                            LlenarTabla();
                            JOptionPane.showMessageDialog(null, "Datos Modificados");
                            Deshabilitar();
                        }
                    }
                 catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Error ->" + e.getMessage());
                 }
               }
            }
           }
         }
        }
       }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getButton() == 1) {
            int fila = jTable1.getSelectedRow();
            Habilitar();
            try {
                String sql = "select * from empleados where em_Id=" + jTable1.getValueAt(fila, 0);
                sent = conn.createStatement();
                ResultSet rs = sent.executeQuery(sql);
                rs.next();
                jTextNombre.setText(rs.getString("Em_Nombre"));
                jTextApellidos.setText(rs.getString("Em_Apellidos"));
                jTextUsuario.setText(rs.getString("Em_Usuario"));
                jPasswordField1.setText(rs.getString("Em_Contraseña"));
                jTextCorreo.setText(rs.getString("Em_Correo"));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
                System.out.println("Error ->" + e.getMessage());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void jTextBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyReleased
        jTextBuscar.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextBuscar.getText(), 1));
            }
        });
        trs = new TableRowSorter(model);
        jTable1.setRowSorter(trs);
    }//GEN-LAST:event_jTextBuscarKeyReleased

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidosKeyTyped
        Utils.validNomApe(jTextApellidos.getText(), evt);
    }//GEN-LAST:event_jTextApellidosKeyTyped

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        Utils.validNomApe(jTextNombre.getText(), evt);
    }//GEN-LAST:event_jTextNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ValApe;
    private javax.swing.JLabel ValEmail;
    private javax.swing.JLabel ValNom;
    private javax.swing.JLabel ValPass;
    private javax.swing.JLabel ValUser;
    private javax.swing.JLabel anuncio;
    private javax.swing.JLabel anuncioB;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
