/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import Funciones.conexion;
import Funciones.utils.Consulta;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guillermo
 */
public class ProductosBE extends javax.swing.JFrame {

    Connection conn;
    Statement sent;
    ResultSet rs;
    DefaultTableModel tabla;

    public ProductosBE() {
        initComponents();
        cargarlistaproductos();
    }

    private void cargarlistaproductos(String dato) {
        try {
            conn = conexion.conectar();
            //String[] Titulo = {"Codigo", "Producto", "Presentación", "Precio", "Stock"};
            //tabla = new DefaultTableModel(null, Titulo);
            tabla = (DefaultTableModel) tbprod.getModel();
            tabla.setRowCount(0);
            String[] Registro = new String[5];
            String mostrar = "SELECT * FROM productos WHERE CONCAT (Pr_Id,'',Pr_Nombre,'',Pr_Presentacion) LIKE '%" + dato + "%'";
            sent = conn.createStatement();
            rs = sent.executeQuery(mostrar);
            while (rs.next()) {
                Registro[0] = rs.getString("Pr_Id");
                Registro[1] = rs.getString("Pr_Nombre");
                Registro[2] = rs.getString("Pr_Presentacion");
                Registro[3] = rs.getString("Pr_Precio");
                Registro[4] = rs.getString("Pr_Cantidad");
                tabla.addRow(Registro);
            }
            tbprod.setModel(tabla);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error ->" + e.getMessage());
        }
    }

    public void cargarlistaproductos() {
        try {
            conn = conexion.conectar();
            //String[] Titulo = {"Codigo", "Producto", "Presentación", "Precio", "Stock"};
            //tabla = new DefaultTableModel(null, Titulo);
            tabla = (DefaultTableModel) tbprod.getModel();
            tabla.setRowCount(0);
            String[] Registro = new String[5];
            String mostrar = "SELECT * FROM productos WHERE CONCAT (Pr_Id,'',Pr_Nombre)";
            sent = conn.createStatement();
            rs = sent.executeQuery(mostrar);
            while (rs.next()) {
                Registro[0] = rs.getString("Pr_Id");
                Registro[1] = rs.getString("Pr_Nombre");
                Registro[2] = rs.getString("Pr_Presentacion");
                Registro[3] = rs.getString("Pr_Precio");
                Registro[4] = rs.getString("Pr_Cantidad");
                tabla.addRow(Registro);
            }
            tbprod.setModel(tabla);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocurrio una falla contacte a su proveedor.", "Falla", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error ->" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbprod = new javax.swing.JTable();
        btncerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtprod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar Productos :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, -1, 20));

        tbprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Presentación", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbprod.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tbprod);
        if (tbprod.getColumnModel().getColumnCount() > 0) {
            tbprod.getColumnModel().getColumn(0).setResizable(false);
            tbprod.getColumnModel().getColumn(1).setResizable(false);
            tbprod.getColumnModel().getColumn(2).setResizable(false);
            tbprod.getColumnModel().getColumn(3).setResizable(false);
            tbprod.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 369, 150));

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        txtprod.setToolTipText("Buscador");
        txtprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprodKeyTyped(evt);
            }
        });
        getContentPane().add(txtprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, -1));

        jLabel2.setText("Escriba el código, el nombre del producto o la presentación");
        jLabel2.setMaximumSize(new java.awt.Dimension(310, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(310, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(310, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 350, 20));

        jLabel3.setText("seleccione el producto y agréguelo.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        tbprod.clearSelection();
        this.setVisible(false);
    }//GEN-LAST:event_btncerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultTableModel tabladet = (DefaultTableModel) VentasE.jTable1.getModel();
            String[] dato = new String[6];

            int fila = tbprod.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un producto.");
            } else {
                String codins = tbprod.getValueAt(fila, 0).toString();
                String desins = tbprod.getValueAt(fila, 1).toString();
                String presins = tbprod.getValueAt(fila, 2).toString();
                String precins = tbprod.getValueAt(fila, 3).toString();

                int mismoProd = 0;

                String cant = JOptionPane.showInputDialog("Ingrese la cantidad deseada del producto.");
                if ((cant.equals("")) || (cant.equals("0"))) {
                    JOptionPane.showMessageDialog(null, "<html>Debe ingresar una cantidad mayor a 0. Intente nuevamente.<br><b>Si desea eliminar un producto utilice el botón Eliminar en la ventana de ventas.</b></html>");
                } else {
                    int canting = Integer.parseInt(cant);
                    if (canting <= 0) {
                        JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad mayor a 0.\nIntente nuevamente.");
                    } else {
                        int comp = Integer.parseInt(Consulta.comparar(codins));
                        if (canting > comp) {
                            JOptionPane.showMessageDialog(null, "No hay suficiente stock del producto.\nIntente nuevamente.");
                        } else {
                            for (int i = 0; i < VentasE.jTable1.getRowCount(); i++) {
                                String com = VentasE.jTable1.getValueAt(i, 0).toString();
                                if (codins.equals(com)) {
                                    tabladet.setValueAt(cant, i, 4);
                                    mismoProd = ++mismoProd;
                                }
                            }
                            if (mismoProd == 0) {

                                dato[0] = codins;
                                dato[1] = desins;
                                dato[2] = presins;
                                dato[3] = precins;
                                dato[4] = cant;
                                tabladet.addRow(dato);
                                VentasE.jTable1.setModel(tabladet);
                                VentasE.calcular();
                            }
                            DefaultTableModel model = (DefaultTableModel) tbprod.getModel();
                            model.setValueAt(comp - canting, fila, 4);
                        }
                    }
                }
            }
        } catch (NullPointerException e) {
            System.out.println("error por cancelación. - " + e.getMessage());
        } catch (HeadlessException | NumberFormatException e) {
            System.out.println("error por cancelación alert. - " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Ingrese solo números.\nIntente nuevamente.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodKeyReleased

        cargarlistaproductos(txtprod.getText());
    }//GEN-LAST:event_txtprodKeyReleased

    private void txtprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodKeyTyped
        char car = evt.getKeyChar();
        if (!Character.isLetterOrDigit(car) && !Character.isSpaceChar(car) && (car != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtprodKeyTyped
int xy, xx;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      xy= evt.getY();
      xx= evt.getX();
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
     int y= evt.getYOnScreen();
      int x= evt.getXOnScreen();
      
this.setLocation(x-xx,y-xy);
   // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ProductosBE().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbprod;
    private javax.swing.JTextField txtprod;
    // End of variables declaration//GEN-END:variables
}
